routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/post/{slug}', 'HomeController@show')->name('post.show');
Route::get('/tag/{slug}', 'HomeController@tag')->name('tag.show');
Route::get('/category/{slug}', 'HomeController@category')->name('category.show');
Route::post('/subscribe', 'SubsController@subscribe');
Route::get('/verify/{token}', 'SubsController@verify');

Route::group(['middleware' => 'auth'], function(){
    Route::get('/logout', 'AuthController@logout');
    Route::get('/profile', 'ProfileController@index');
    Route::post('/profile', 'ProfileController@store');
    Route::post('/comment', 'CommentsController@store');
});
Route::group(['middleware' => 'guest'], function(){
    Route::get('/register', 'AuthController@registerForm');
    Route::post('/register', 'AuthController@register');

    Route::get('/login', 'AuthController@loginForm')->name('login');
    Route::post('/login', 'AuthController@login');
});




Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'namespace' => 'Admin'], function (){
    Route::get('/', 'DashboardController@index')-> name('dashboard');
    Route::get('/comments', 'CommentsController@index')->name('comments.index');
    Route::get('/comments/toggle/{id}', 'CommentsController@toggle');

    Route::resource('/categories', 'CategoriesController');
    Route::resource('/tags', 'TagsController');
    Route::resource('/users', 'UsersController');
    Route::resource('/posts', 'PostsController');
    Route::resource('/subscribers','SubscribersController');

    Route::delete('/comments/{id}/destroy', 'CommentsController@destroy')->name('comments.destroy');

});

//Auth::routes();

resources/views/pages/_sidebar.blade.php
<div class="col-md-4" data-sticky_column>
    <div class="primary-sidebar">

        <aside class="widget news-letter">
            <h3 class="widget-title text-uppercase text-center">Get Newsletter</h3>

            @include('admin.errors')

            <form action="/subscribe" method="post">
                {{ csrf_field() }}
                <input type="email" name="email" placeholder="Your email address">
                <input type="submit" value="Subscribe Now"
                       class="text-uppercase text-center btn btn-subscribe">
            </form>

        </aside>
        <aside class="widget">
            <h3 class="widget-title text-uppercase text-center">Popular Posts</h3>

            @foreach($popularPosts as $post)
                <div class="popular-post">
                    <a href="{{ route('post.show', $post->slug) }}" class="popular-img">
                        <img src="{{ $post->getImage() }}" alt="">
                        <div class="p-overlay"></div>
                    </a>

                    <div class="p-content">
                        <a href="{{ route('post.show', $post->slug) }}" class="text-uppercase">{{ $post->title }}</a>
                        <span class="p-date">{{ $post->getDate() }}</span>

                    </div>
                </div>
            @endforeach

        </aside>
        <aside class="widget">
            <h3 class="widget-title text-uppercase text-center">Featured Posts</h3>

            <div id="widget-feature" class="owl-carousel">
                @foreach($featuredPosts as $post)
                    <div class="item">
                    <div class="feature-content">
                        <img src="{{ $post->getImage() }}" alt="">

                        <a href="{{ route('post.show', $post->slug) }}" class="overlay-text text-center">
                            <h5 class="text-uppercase">{{ $post->title }}</h5>
                            <p>{!! $post->description !!}</p>
                        </a>
                    </div>
                </div>
                @endforeach
            </div>
        </aside>
        <aside class="widget pos-padding">
            <h3 class="widget-title text-uppercase text-center">Recent Posts</h3>

            @foreach($recentPosts as $post)
                <div class="thumb-latest-posts">
                    <div class="media">
                        <div class="media-left">
                            <a href="{{ route('post.show', $post->slug) }}" class="popular-img">
                                <img src="{{ $post->getImage() }}" alt="">
                                <div class="p-overlay"></div>
                            </a>
                        </div>
                        <div class="p-content">
                            <a href="{{ route('post.show', $post->slug) }}" class="text-uppercase">
                                {{ $post->title }}
                            </a>
                            <span class="p-date">{{ $post->getDate() }}</span>
                        </div>
                    </div>
                </div>
            @endforeach
        </aside>
        <aside class="widget border pos-padding">
            <h3 class="widget-title text-uppercase text-center">Categories</h3>
            <ul>
                @foreach($categories as $category)
                    <li>
                    <a href="{{ route('category.show', $category->slug) }}">{{ $category->title }}</a>
                    <span class="post-count pull-right"> ({{ $category->posts->count() }})</span>
                </li>
                @endforeach
            </ul>
        </aside>
    </div>
</div>

resources/views/pages/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="col-md-8">

                    @foreach($posts as $post)
                        <article class="post">
                            <div class="post-thumb">
                                <a href="{{ route('post.show', $post->slug) }}"><img src="{{ $post->getImage() }}" alt=""></a>

                                <a href="{{ route('post.show', $post->slug) }}" class="post-thumb-overlay text-center">
                                    <div class="text-uppercase text-center">View Post</div>
                                </a>
                            </div>
                            <div class="post-content">
                                <header class="entry-header text-center text-uppercase">
                                    @if($post->hasCategory())
                                        <h6>
                                            <a href="{{route('categories.show', $post->category->slug)}}">{{ $post->getCategoryTitle()}} </a>
                                        </h6>
                                    @endif
                                    <h1 class="entry-title"><a href="{{ route('post.show', $post->slug) }}">{{ $post->title }}</a></h1>


                                </header>
                                <div class="entry-content">
                                    <p>{!! $post->description !!}</p>

                                    <div class="btn-continue-reading text-center text-uppercase">
                                        <a href="{{ route('post.show', $post->slug) }}" class="more-link">Continue Reading</a>
                                    </div>
                                </div>
                                <div class="social-share">
                                    <span class="social-share-title pull-left text-capitalize">By <a href="#">{{ $post->author->name }}</a> {{ $post->getDate() }}</span>
                                    <ul class="text-center pull-right">
                                        <li><a class="s-facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                                        <li><a class="s-twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                                        <li><a class="s-google-plus" href="#"><i class="fa fa-google-plus"></i></a></li>
                                        <li><a class="s-linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                                        <li><a class="s-instagram" href="#"><i class="fa fa-instagram"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </article>
                    @endforeach

                    {{ $posts->links() }}

                </div>
                @include('pages._sidebar')
            </div>
        </div>
    </div>
@endsection

resources/views/pages/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="row">
                        @foreach($posts as $post)
                            <div class="col-md-6">
                            <article class="post post-grid">
                                <div class="post-thumb">
                                    <a href="{{route('post.show', $post->slug)}}"><img src="{{$post->getImage()}}" alt=""></a>

                                    <a href="{{route('post.show', $post->slug)}}" class="post-thumb-overlay text-center">
                                        <div class="text-uppercase text-center">View Post</div>
                                    </a>
                                </div>
                                <div class="post-content">
                                    <header class="entry-header text-center text-uppercase">
                                        <h6><a href="{{route('categories.show', $post->category->slug)}}">{{$post->getCategory}}</a></h6>

                                        <h1 class="entry-title">
                                            <a href="{{route('post.show', $post->slug)}}">
                                                {{$post->title}}
                                            </a>
                                        </h1>


                                    </header>
                                    <div class="entry-content">
                                        {!! $post->description !!}
                                        <div class="social-share">
                                            <span class="social-share-title pull-left text-capitalize">By Rubel On {{$post->getDate()}}</span>
                                        </div>
                                    </div>
                                </div>

                            </article>
                        </div>
                        @endforeach
                    </div>
                    {{$posts->links()}}
                </div>
                @include('pages._sidebar')
            </div>
        </div>
    </div>
@endsection

resources/views/pages/login.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="col-md-8">

                    <div class="leave-comment mr0"><!--leave comment-->

                        <h3 class="text-uppercase">Login</h3>
                        @if(session('status'))
                            <div class="alert alert-danger">{{ session('status') }}</div>
                        @endif
                        @include('admin.errors')
                        <br>
                        <form class="form-horizontal contact-form" role="form" method="post" action="/login">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" class="form-control" id="email" name="email"
                                           placeholder="Email" value="{{ old('email') }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="password" class="form-control" id="password" name="password"
                                           placeholder="password">
                                </div>
                            </div>
                            <button type="submit"  class="btn send-btn">Login</button>

                        </form>
                    </div><!--end leave comment-->
                </div>
                @include('pages._sidebar')
            </div>
        </div>
    </div>
@endsection

resources/views/pages/profile.blade.php
@extends('layouts.app')


@section('content')
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="col-md-8">

                    <div class="leave-comment mr0"><!--leave comment-->

                        @if(session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif
                        <h3 class="text-uppercase">My profile</h3>
                        @include('admin.errors')
                        <br>
                        <img src="{{ $user->getAvatar() }}" alt="" class="profile-image">
                        <form class="form-horizontal contact-form" role="form"
                              enctype="multipart/form-data"
                              method="post"
                              action="/profile">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" class="form-control" id="name" name="name"
                                           placeholder="Name" value="{{ $user->name }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="email" class="form-control" id="email" name="email"
                                           placeholder="Email" value="{{ $user->email }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" class="form-control" id="password" name="password"
                                           placeholder="password">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="file" class="form-control" id="image" name="avatar">
                                </div>
                            </div>
                            <button type="submit"  class="btn send-btn">Update</button>

                        </form>
                    </div><!--end leave comment-->
                </div>
                @include('pages._sidebar')
            </div>
        </div>
    </div>
@endsection

resources/views/pages/register.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="col-md-8">

                    <div class="leave-comment mr0"><!--leave comment-->

                        <h3 class="text-uppercase">Register</h3>
                        @include('admin.errors')
                        <br>

                        <form class="form-horizontal contact-form" role="form" method="post" action="/register">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" class="form-control" id="name" name="name"
                                           placeholder="Name" value="{{ old('name') }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" class="form-control" id="email" name="email"
                                           placeholder="Email" value="{{ old('email') }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="password" class="form-control" id="password" name="password"
                                           placeholder="password">
                                </div>
                            </div>
                            <button type="submit" class="btn send-btn">Register</button>

                        </form>
                    </div><!--end leave comment-->
                </div>
                @include('pages._sidebar')
            </div>
        </div>
    </div>
@endsection

resources/views/pages/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="col-md-8">


                    <article class="post">
                        <div class="post-thumb">
                            <a href="blog.html"><img src="{{ $post->getImage() }}" alt=""></a>
                        </div>
                        <div class="post-content">
                            <header class="entry-header text-center text-uppercase">
                                @if($post->hasCategory())
                                    <h6>
                                        <a href="{{route('categories.show', $post->category->slug)}}">{{ $post->getCategoryTitle()}} </a>
                                    </h6>
                                @endif

                                <h1 class="entry-title"><a href="blog.html">{{ $post->title }}</a></h1>


                            </header>
                            <div class="entry-content">
                                {!! $post->content !!}
                            </div>
                            <div class="decoration">
                                @foreach($post->tags as $tag)
                                    <a href="{{route('tag.show', $tag->slug)}}" class="btn btn-default">{{ $tag->title }}</a>
                                @endforeach
                            </div>

                            <div class="social-share">
							<span
                                class="social-share-title pull-left text-capitalize">By Rubel On {{ $post->getDate() }}</span>
                                <ul class="text-center pull-right">
                                    <li><a class="s-facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a class="s-twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a class="s-google-plus" href="#"><i class="fa fa-google-plus"></i></a></li>
                                    <li><a class="s-linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                                    <li><a class="s-instagram" href="#"><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </article>
                    <div class="top-comment"><!--top comment-->
                        <img src="/images/comment.jpg" class="pull-left img-circle" alt="">
                        <h4>Rubel Miah</h4>

                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy hello ro mod tempor
                            invidunt ut labore et dolore magna aliquyam erat.</p>
                    </div><!--top comment end-->
                    <div class="row"><!--blog next previous-->
                        <div class="col-md-6">
                            @if($post->hasPrevious())
                            <div class="single-blog-box">
                                <a href="{{ route('post.show', $post->getPrevious()->slug) }}">
                                    <img src="{{ $post->getPrevious()->getImage() }}" alt="">

                                    <div class="overlay">

                                        <div class="promo-text">
                                            <p><i class=" pull-left fa fa-angle-left"></i></p>
                                            <h5>{{ $post->getPrevious()->title }}</h5>
                                        </div>
                                    </div>

                                </a>
                            </div>
                            @endif
                        </div>
                        <div class="col-md-6">
                            @if($post->hasNext())
                            <div class="single-blog-box">
                                <a href="{{ route('post.show', $post->getNext()->slug) }}">
                                    <img src="{{ $post->getNext()->getImage() }}" alt="">

                                    <div class="overlay">
                                        <div class="promo-text">
                                            <p><i class=" pull-right fa fa-angle-right"></i></p>
                                            <h5>{{ $post->getNext()->title }}</h5>

                                        </div>
                                    </div>
                                </a>
                            </div>
                            @endif
                        </div>
                    </div><!--blog next previous end-->
                    <div class="related-post-carousel"><!--related post carousel-->
                        <div class="related-heading">
                            <h4>You might also like</h4>
                        </div>
                        <div class="items">
                            @foreach($post->related() as $item)
                            <div class="single-item">
                                <a href="{{ route('post.show', $item->slug) }}">
                                    <img src="{{ $item->getImage() }}" alt="">

                                    <p>{{ $item->title }}</p>
                                </a>
                            </div>
                            @endforeach
                        </div>
                    </div><!--related post carousel-->

                    @if(!$post->comments->isEmpty())
                        @foreach($post->getComments() as $comment)
                                <div class="bottom-comment"><!--bottom comment-->
                                    <h4>3 comments</h4>

                                    <div class="comment-img">
                                        <img class="img-circle" src="{{ $comment->author->getAvatar() }}" width="75" height="75" alt="">
                                    </div>

                                    <div class="comment-text">

                                        <h5>{{ $comment->author->name }}</h5>

                                        <p class="comment-date">
                                            {{ $comment->created_at->diffForHumans() }}
                                        </p>


                                        <p class="para">{{ $comment->text }}</p>
                                    </div>
                                </div>
                            @endforeach
                    @endif
                    <!-- end bottom comment-->

                    @if(Auth::check())
                    <div class="leave-comment"><!--leave comment-->
                        <h4>Leave a reply</h4>

                        <form class="form-horizontal contact-form" role="form" method="post" action="/comment">
                            {{ csrf_field() }}
                            <input type="hidden" name="post_id" value="{{ $post->id }}">
                            <div class="form-group">
                                <div class="col-md-12">
										<textarea class="form-control" rows="6" name="message"
                                                  placeholder="Write Massage"></textarea>
                                </div>
                            </div>
                            <button class="btn send-btn">Post Comment</button>
                        </form>
                    </div><!--end leave comment-->
                    @endif
                </div>
                @include('pages._sidebar')
            </div>
        </div>
    </div>
@endsection